/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface CampanhaAdministradores {
  campanha_id: string;
  id_usuario: string;
}

export interface Campanhas {
  criada_em: Generated<Timestamp>;
  id: string;
  id_plataforma: string;
  titulo: string;
}

export interface Cats {
  created_at: Generated<Timestamp>;
  id: string;
  name: string;
}

export interface Contas {
  criada_em: Generated<Timestamp>;
  id: string;
  id_usuario: string;
  permissoes: Generated<string[]>;
}

export interface Contribuicoes {
  campanha_id: string;
  contribuinte_email: string | null;
  contribuinte_nome: string | null;
  criada_em: Generated<Timestamp>;
  grupo: string | null;
  id: string;
  id_opcao_contribuicao: string;
  imagem_url: string | null;
  nome: string;
  status: string;
  valor: number;
}

export interface OpcoesContribuicao {
  campanha_id: string;
  id: string;
  tipo: string;
}

export interface Recebedores {
  campanha_id: string;
  chave_pix: string;
  criada_em: Generated<Timestamp>;
  id: string;
  is_active: Generated<boolean>;
  nome_titular: string;
  tipo_chave_pix: string;
}

export interface Usuarios {
  criado_em: Generated<Timestamp>;
  email: string;
  id: string;
  id_conta: string;
  id_plataforma: string;
  nome_exibicao: string;
}

export interface DB {
  campanha_administradores: CampanhaAdministradores;
  campanhas: Campanhas;
  cats: Cats;
  contas: Contas;
  contribuicoes: Contribuicoes;
  opcoes_contribuicao: OpcoesContribuicao;
  recebedores: Recebedores;
  usuarios: Usuarios;
}
