/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Accounts {
  access_token: string | null;
  access_token_expires_at: Timestamp | null;
  account_id: string;
  created_at: Generated<Timestamp>;
  id: string;
  id_token: string | null;
  password: string | null;
  provider_id: string;
  refresh_token: string | null;
  refresh_token_expires_at: Timestamp | null;
  scope: string | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface CampanhaAdministradores {
  campanha_id: string;
  id_usuario: string;
}

export interface Campanhas {
  criada_em: Generated<Timestamp>;
  id: string;
  id_plataforma: string;
  titulo: string;
}

export interface Cats {
  created_at: Generated<Timestamp>;
  id: string;
  name: string;
}

export interface Contas {
  criada_em: Generated<Timestamp>;
  id: string;
  id_usuario: string;
  permissoes: Generated<string[]>;
}

export interface Contribuicoes {
  campanha_id: string;
  contribuinte_email: string | null;
  contribuinte_nome: string | null;
  criada_em: Generated<Timestamp>;
  grupo: string | null;
  id: string;
  id_opcao_contribuicao: string;
  imagem_url: string | null;
  nome: string;
  status: string;
  valor: number;
}

export interface OpcoesContribuicao {
  campanha_id: string;
  id: string;
  tipo: string;
}

export interface Pagamentos {
  atualizado_em: Timestamp;
  criado_em: Timestamp;
  id: string;
  intencao_amount_cents: number;
  intencao_composicao_valores: Json;
  intencao_criada_em: Timestamp;
  intencao_external_ref: string | null;
  intencao_id: string;
  intencao_id_contribuicao: string;
  intencao_metodo: string;
  status: string;
  transacao_externa: Json | null;
}

export interface RateLimit {
  count: Generated<number>;
  id: string;
  key: string;
  last_request: Int8;
}

export interface Recebedores {
  campanha_id: string;
  chave_pix: string;
  criada_em: Generated<Timestamp>;
  id: string;
  is_active: Generated<boolean>;
  nome_titular: string;
  tipo_chave_pix: string;
}

export interface Sessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: string;
  ip_address: string | null;
  token: string;
  updated_at: Generated<Timestamp>;
  user_agent: string | null;
  user_id: string;
}

export interface Users {
  created_at: Generated<Timestamp>;
  email: string;
  email_verified: Generated<boolean>;
  id: string;
  id_plataforma: string;
  image: string | null;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface Usuarios {
  criado_em: Generated<Timestamp>;
  email: string;
  id: string;
  id_conta: string;
  id_plataforma: string;
  nome_exibicao: string;
  slug: string;
}

export interface Verifications {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: string;
  identifier: string;
  updated_at: Generated<Timestamp>;
  value: string;
}

export interface DB {
  accounts: Accounts;
  campanha_administradores: CampanhaAdministradores;
  campanhas: Campanhas;
  cats: Cats;
  contas: Contas;
  contribuicoes: Contribuicoes;
  opcoes_contribuicao: OpcoesContribuicao;
  pagamentos: Pagamentos;
  rate_limit: RateLimit;
  recebedores: Recebedores;
  sessions: Sessions;
  users: Users;
  usuarios: Usuarios;
  verifications: Verifications;
}
