/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Accounts {
  access_token: string | null;
  access_token_expires_at: Timestamp | null;
  account_id: string;
  created_at: Generated<Timestamp>;
  id: string;
  id_token: string | null;
  password: string | null;
  provider_id: string;
  refresh_token: string | null;
  refresh_token_expires_at: Timestamp | null;
  scope: string | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface CampanhaAdministradores {
  campanha_id: string;
  id_usuario: string;
}

export interface Campanhas {
  criada_em: Generated<Timestamp>;
  id: string;
  id_plataforma: string;
  titulo: string;
}

export interface Cats {
  created_at: Generated<Timestamp>;
  id: string;
  name: string;
}

export interface Contas {
  criada_em: Generated<Timestamp>;
  id: string;
  id_usuario: string;
  permissoes: Generated<string[]>;
}

export interface Contribuicoes {
  // Plan 0015 / migration 019: status + contribuinte_* dropped.
  campanha_id: string;
  criada_em: Generated<Timestamp>;
  grupo: string | null;
  id: string;
  id_opcao_contribuicao: string;
  imagem_url: string | null;
  nome: string;
  valor: number;
}

export interface Convidados {
  id: string;
  lista_id: string;
  nome: string;
  numero_celular: string;
  presenca: string;
}

export interface Convites {
  atualizado_em: Generated<Timestamp>;
  criado_em: Generated<Timestamp>;
  fonte: string;
  id: string;
  id_evento: string;
  imagem_url: string | null;
  mensagem: string;
  modelo: string;
  nome_exibido: string;
  paleta: string;
  remetente: string;
}

export interface Eventos {
  atualizado_em: Generated<Timestamp>;
  criado_em: Generated<Timestamp>;
  data_hora: Timestamp;
  endereco: string | null;
  id: string;
  id_campanha: string;
  modalidade: string;
  tipo_evento: string;
}

export interface LancamentosFinanceiros {
  // Plan 0015 / migration 019: status + matura_em dropped;
  // transferido_em + cancelado_em added (both nullable).
  // aperture-s03dr / migration 021: id_repasse added (nullable —
  // points at the pending/aprovado repasse_recebedor that claimed
  // this lancamento, if any).
  amount_cents: number;
  cancelado_em: Timestamp | null;
  criado_em: Timestamp;
  id: string;
  id_campanha: string | null;
  id_contribuicao: string;
  id_pagamento: string;
  id_repasse: string | null;
  tipo: string;
  transferido_em: Timestamp | null;
}

export interface ListasDeConvidados {
  atualizado_em: Generated<Timestamp>;
  criado_em: Generated<Timestamp>;
  id: string;
  id_evento: string;
  link_confirmacao: string;
}

export interface OpcoesContribuicao {
  campanha_id: string;
  id: string;
  tipo: string;
}

export interface Pagamentos {
  // Plan 0015 / migration 019: intencao_contribuinte_{nome,email,mensagem}
  // added (all nullable; populated by webhook at checkout.session.completed).
  // Plan 0015 / migration 020 (aperture-mjgxe):
  // intencao_balance_transaction_available_on added (nullable).
  atualizado_em: Timestamp;
  criado_em: Timestamp;
  id: string;
  intencao_amount_cents: number;
  intencao_balance_transaction_available_on: Timestamp | null;
  intencao_charge_external_ref: string | null;
  intencao_composicao_valores: Json;
  intencao_contribuinte_email: string | null;
  intencao_contribuinte_mensagem: string | null;
  intencao_contribuinte_nome: string | null;
  intencao_criada_em: Timestamp;
  intencao_external_ref: string | null;
  intencao_id: string;
  intencao_id_contribuicao: string;
  intencao_metodo: string;
  intencao_payment_intent_external_ref: string | null;
  status: string;
  transacao_externa: Json | null;
}

export interface PaymentWebhookEvents {
  event_type: string;
  id: string;
  pagamento_id: string | null;
  processed_at: Timestamp | null;
  processing_error: string | null;
  provider: Generated<string>;
  provider_event_id: string;
  raw_payload: Json;
  received_at: Generated<Timestamp>;
  signature_header: string;
  signature_valid: boolean;
}

export interface RateLimit {
  count: Generated<number>;
  id: string;
  key: string;
  last_request: Int8;
}

export interface Recebedores {
  campanha_id: string;
  chave_pix: string;
  criada_em: Generated<Timestamp>;
  id: string;
  is_active: Generated<boolean>;
  nome_titular: string;
  tipo_chave_pix: string;
}

export interface RepassesRecebedor {
  // aperture-s03dr / migration 021: aprovado_em + bank_transfer_ref added
  // (both nullable); status CHECK extended to include 'aprovado'.
  amount_cents: number;
  aprovado_em: Timestamp | null;
  bank_transfer_ref: string | null;
  id: string;
  id_campanha: string;
  solicitado_em: Timestamp;
  status: string;
}

export interface Sessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: string;
  ip_address: string | null;
  token: string;
  updated_at: Generated<Timestamp>;
  user_agent: string | null;
  user_id: string;
}

export interface Users {
  created_at: Generated<Timestamp>;
  email: string;
  email_verified: Generated<boolean>;
  id: string;
  id_plataforma: string;
  image: string | null;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface Usuarios {
  criado_em: Generated<Timestamp>;
  email: string;
  id: string;
  id_conta: string;
  id_plataforma: string;
  nome_exibicao: string;
  slug: string;
}

export interface Verifications {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: string;
  identifier: string;
  updated_at: Generated<Timestamp>;
  value: string;
}

export interface DB {
  accounts: Accounts;
  campanha_administradores: CampanhaAdministradores;
  campanhas: Campanhas;
  cats: Cats;
  contas: Contas;
  contribuicoes: Contribuicoes;
  convidados: Convidados;
  convites: Convites;
  eventos: Eventos;
  lancamentos_financeiros: LancamentosFinanceiros;
  listas_de_convidados: ListasDeConvidados;
  opcoes_contribuicao: OpcoesContribuicao;
  pagamentos: Pagamentos;
  payment_webhook_events: PaymentWebhookEvents;
  rate_limit: RateLimit;
  recebedores: Recebedores;
  repasses_recebedor: RepassesRecebedor;
  sessions: Sessions;
  users: Users;
  usuarios: Usuarios;
  verifications: Verifications;
}
