import { z } from 'zod/v4';

export const ModeloConviteSchema = z.enum([
  'scrapbook',
  'varal-de-mimos',
  'balao-de-ar',
  'jardim-romantico',
  'lavanda',
  'floresta-magica',
  'roupinhas-e-coracoes',
  'berco-floral',
  'arco-iris-boho',
  'margaridas',
  'girafinha-bailarina',
  'safari',
  'elefantinho',
  'aviao-nas-nuvens',
  'balao-dourado',
  'baloes-no-ceu',
  'bandeirinhas-ursinho',
  'bichinhos-do-bosque',
  'bola-na-rede',
  'borboleta-encantada',
  'campo-de-futebol',
  'coelhinho-e-bebe',
  'dinossauro-aviador',
  'dinossauro-azul',
  'dormitorio',
  'elefante-no-luar',
  'flor-amarela',
  'florestas-azuis-aquarela',
  'fundo-marinho',
  'futebol-divertido',
  'girafa-estrelada',
  'patinho-laco-azul',
  'patinho-xadrez',
  'quadra-de-futebol',
  'roupinhas-delicada',
  'urso-com-baloes',
  'urso-nas-nuvens',
  'xadrez-azul-suave',
]);

export type ModeloConvite = z.infer<typeof ModeloConviteSchema>;
